[2022-12-08T22:43:30.277+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: back_in_avro.First_task_backup manual__2022-12-08T22:43:28.562059+00:00 [queued]>
[2022-12-08T22:43:30.295+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: back_in_avro.First_task_backup manual__2022-12-08T22:43:28.562059+00:00 [queued]>
[2022-12-08T22:43:30.297+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-08T22:43:30.298+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 6
[2022-12-08T22:43:30.300+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-08T22:43:30.332+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): First_task_backup> on 2022-12-08 22:43:28.562059+00:00
[2022-12-08T22:43:30.342+0000] {standard_task_runner.py:55} INFO - Started process 7056 to run task
[2022-12-08T22:43:30.348+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'back_in_avro', 'First_task_backup', 'manual__2022-12-08T22:43:28.562059+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/dag_back_in_avro.py', '--cfg-path', '/tmp/tmprhi2wl3f']
[2022-12-08T22:43:30.352+0000] {standard_task_runner.py:83} INFO - Job 29: Subtask First_task_backup
[2022-12-08T22:43:30.460+0000] {task_command.py:389} INFO - Running <TaskInstance: back_in_avro.First_task_backup manual__2022-12-08T22:43:28.562059+00:00 [running]> on host c4fdd5f7672d
[2022-12-08T22:43:30.556+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Martin_Jurado
AIRFLOW_CTX_DAG_ID=back_in_avro
AIRFLOW_CTX_TASK_ID=First_task_backup
AIRFLOW_CTX_EXECUTION_DATE=2022-12-08T22:43:28.562059+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-08T22:43:28.562059+00:00
[2022-12-08T22:43:30.605+0000] {logging_mixin.py:137} INFO - There is information in the database
[2022-12-08T22:43:30.682+0000] {python.py:177} INFO - Done. Returned value was: None
[2022-12-08T22:43:30.695+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=back_in_avro, task_id=First_task_backup, execution_date=20221208T224328, start_date=20221208T224330, end_date=20221208T224330
[2022-12-08T22:43:30.763+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2022-12-08T22:43:30.795+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
