[2022-12-11T12:49:45.055+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: back_in_avro.First_task_backup scheduled__2022-12-11T11:00:00+00:00 [queued]>
[2022-12-11T12:49:45.070+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: back_in_avro.First_task_backup scheduled__2022-12-11T11:00:00+00:00 [queued]>
[2022-12-11T12:49:45.071+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-11T12:49:45.072+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 6
[2022-12-11T12:49:45.073+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-11T12:49:45.091+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): First_task_backup> on 2022-12-11 11:00:00+00:00
[2022-12-11T12:49:45.100+0000] {standard_task_runner.py:55} INFO - Started process 19188 to run task
[2022-12-11T12:49:45.106+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'back_in_avro', 'First_task_backup', 'scheduled__2022-12-11T11:00:00+00:00', '--job-id', '121', '--raw', '--subdir', 'DAGS_FOLDER/dag_back_in_avro.py', '--cfg-path', '/tmp/tmp1_amdebt']
[2022-12-11T12:49:45.110+0000] {standard_task_runner.py:83} INFO - Job 121: Subtask First_task_backup
[2022-12-11T12:49:45.224+0000] {task_command.py:389} INFO - Running <TaskInstance: back_in_avro.First_task_backup scheduled__2022-12-11T11:00:00+00:00 [running]> on host c4fdd5f7672d
[2022-12-11T12:49:45.331+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Martin_Jurado
AIRFLOW_CTX_DAG_ID=back_in_avro
AIRFLOW_CTX_TASK_ID=First_task_backup
AIRFLOW_CTX_EXECUTION_DATE=2022-12-11T11:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-11T11:00:00+00:00
[2022-12-11T12:49:45.445+0000] {logging_mixin.py:137} INFO - There is information in the database
[2022-12-11T12:49:45.530+0000] {python.py:177} INFO - Done. Returned value was: None
[2022-12-11T12:49:45.544+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=back_in_avro, task_id=First_task_backup, execution_date=20221211T110000, start_date=20221211T124945, end_date=20221211T124945
[2022-12-11T12:49:45.602+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2022-12-11T12:49:45.627+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
