[2022-12-11T05:58:51.829+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: back_in_avro.First_task_backup scheduled__2022-12-11T04:00:00+00:00 [queued]>
[2022-12-11T05:58:51.847+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: back_in_avro.First_task_backup scheduled__2022-12-11T04:00:00+00:00 [queued]>
[2022-12-11T05:58:51.848+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-11T05:58:51.849+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 6
[2022-12-11T05:58:51.850+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-11T05:58:51.874+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): First_task_backup> on 2022-12-11 04:00:00+00:00
[2022-12-11T05:58:51.883+0000] {standard_task_runner.py:55} INFO - Started process 18982 to run task
[2022-12-11T05:58:51.889+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'back_in_avro', 'First_task_backup', 'scheduled__2022-12-11T04:00:00+00:00', '--job-id', '108', '--raw', '--subdir', 'DAGS_FOLDER/dag_back_in_avro.py', '--cfg-path', '/tmp/tmptcj9g6zg']
[2022-12-11T05:58:51.893+0000] {standard_task_runner.py:83} INFO - Job 108: Subtask First_task_backup
[2022-12-11T05:58:52.010+0000] {task_command.py:389} INFO - Running <TaskInstance: back_in_avro.First_task_backup scheduled__2022-12-11T04:00:00+00:00 [running]> on host c4fdd5f7672d
[2022-12-11T05:58:52.143+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Martin_Jurado
AIRFLOW_CTX_DAG_ID=back_in_avro
AIRFLOW_CTX_TASK_ID=First_task_backup
AIRFLOW_CTX_EXECUTION_DATE=2022-12-11T04:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-11T04:00:00+00:00
[2022-12-11T05:58:52.200+0000] {logging_mixin.py:137} INFO - There is information in the database
[2022-12-11T05:58:52.368+0000] {python.py:177} INFO - Done. Returned value was: None
[2022-12-11T05:58:52.399+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=back_in_avro, task_id=First_task_backup, execution_date=20221211T040000, start_date=20221211T055851, end_date=20221211T055852
[2022-12-11T05:58:52.469+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2022-12-11T05:58:52.514+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
