[2022-12-10T03:57:17.946+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: back_in_avro.First_task_backup scheduled__2022-12-10T02:00:00+00:00 [queued]>
[2022-12-10T03:57:18.083+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: back_in_avro.First_task_backup scheduled__2022-12-10T02:00:00+00:00 [queued]>
[2022-12-10T03:57:18.090+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-10T03:57:18.099+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 6
[2022-12-10T03:57:18.107+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-10T03:57:18.433+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): First_task_backup> on 2022-12-10 02:00:00+00:00
[2022-12-10T03:57:18.569+0000] {standard_task_runner.py:55} INFO - Started process 16833 to run task
[2022-12-10T03:57:18.651+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'back_in_avro', 'First_task_backup', 'scheduled__2022-12-10T02:00:00+00:00', '--job-id', '82', '--raw', '--subdir', 'DAGS_FOLDER/dag_back_in_avro.py', '--cfg-path', '/tmp/tmp093k5inf']
[2022-12-10T03:57:18.692+0000] {standard_task_runner.py:83} INFO - Job 82: Subtask First_task_backup
[2022-12-10T03:57:20.044+0000] {task_command.py:389} INFO - Running <TaskInstance: back_in_avro.First_task_backup scheduled__2022-12-10T02:00:00+00:00 [running]> on host c4fdd5f7672d
[2022-12-10T03:57:21.680+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Martin_Jurado
AIRFLOW_CTX_DAG_ID=back_in_avro
AIRFLOW_CTX_TASK_ID=First_task_backup
AIRFLOW_CTX_EXECUTION_DATE=2022-12-10T02:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-10T02:00:00+00:00
[2022-12-10T03:57:21.990+0000] {logging_mixin.py:137} INFO - There is information in the database
[2022-12-10T03:57:22.515+0000] {python.py:177} INFO - Done. Returned value was: None
[2022-12-10T03:57:22.741+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=back_in_avro, task_id=First_task_backup, execution_date=20221210T020000, start_date=20221210T035717, end_date=20221210T035722
[2022-12-10T03:57:23.085+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2022-12-10T03:57:23.551+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
